apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            - name: DB_HOST
              value: postgres.cvfmkdysehyr.eu-central-1.rds.amazonaws.com:5432
            - name: DB_NAME
              value: reporter
            - name: DB_USERNAME
              value: reporter
            - name: DB_PASSWORD
              value: reporter