apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: pingpong
    app.kubernetes.io/created-by: ArgoCD
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: ping
    app.kubernetes.io/version: "1.0"
  name: app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: pingpong
    app.kubernetes.io/created-by: ArgoCD
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: ping
    app.kubernetes.io/version: "1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: pingpong
    app.kubernetes.io/created-by: ArgoCD
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: ping
    app.kubernetes.io/version: "1.0"
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pingpong
      app.kubernetes.io/created-by: ArgoCD
      app.kubernetes.io/managed-by: ArgoCD
      app.kubernetes.io/name: ping
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pingpong
        app.kubernetes.io/created-by: ArgoCD
        app.kubernetes.io/managed-by: ArgoCD
        app.kubernetes.io/name: ping
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
      - env:
        - name: ARTEMIS_URL
          valueFrom:
            configMapKeyRef:
              key: ARTEMIS_URL
              name: artemis-configuration
        - name: ARTEMIS_USERNAME
          valueFrom:
            secretKeyRef:
              key: ARTEMIS_USERNAME
              name: artemis-credentials
        - name: ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ARTEMIS_PASSWORD
              name: artemis-credentials
        - name: spring_profiles_active
          value: prod
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/name']
        envFrom: []
        image: 238356400807.dkr.ecr.eu-central-1.amazonaws.com/ping:f3d1fcb
        name: pong
        ports:
        - containerPort: 8080
