apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/app

components:
  - ../../components/patches/configs/postgres

patchesStrategicMerge:
  - generated-image-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app
    path: patch-container-name.yaml

namePrefix: reporter-

commonLabels:
  app.kubernetes.io/name: reporter
  app.kubernetes.io/version: '1.0'
  app.kubernetes.io/component: pingpong
