apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            - name: REPORTER_BASE_URL
              value: http://reporter-app:80