apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            - name: FRUITS_BASE_URL
              value: https://www.fruityvice.com/api/fruit/all