apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          ports:
            - containerPort: 8080
          env:
            - name: spring_profiles_active
              value: prod
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
          envFrom: []